name: "XIV Bone Cleaner"
id_name: "xivbc"
author: "G3ru1a"
version: "0.3"
blender: "4.0.0"
location: "View3D > UI > XIV Bone Cleaner"
description: "Cleans up the bones from a Meddle Exported .gltf Model"
warning: ""
doc_url: ""
category: "XIV Bone Cleaner 0.3"
